SELECT MEMBER.LName, MEMBER.PID,MEMBER_ROLE.RoleID, MEMBER_ROLE.SemesterID
	FROM MEMBER
	INNER JOIN MEMBER_ROLE ON MEMBER.PID = MEMBER_ROLE.PID
	WHERE MEMBER.LName = 'Gaspard' AND MEMBER_ROLE.SemesterID = 'fa16'
